In [1]:
# pandas
import pandas as pd
from pandas import Series,DataFrame

# numpy, matplotlib, seaborn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

pd.set_option('max_colwidth', 100)
pd.options.display.max_rows = 100

In [3]:
import gc
from const import *
import utils, predict

In [77]:
# reload(predict)
reload(utils)

In [4]:
# name = 'XGBClassifier_colsample_bytree:0.8_learning_rate:0.1_max_depth:8_n_estimators:150_scale_pos_weight:2_seed:0_subsample:0.8_07-26-20-48-33.pkl'
name = 'Booster_bagging_fraction:0.85_bagging_freq:3_categorical_column:[0, 1, 2]_feature_fraction:0.7_learning_rate:0.03_max_bin:255_max_depth:8_num_leaves:170_08-15-00-36-41.pkl'
xgb_model = utils.load_model(name)

In [5]:
df_feature_gain = utils.get_feature_score(xgb_model._Booster.get_score(importance_type='gain'))

AttributeError: 'Booster' object has no attribute '_Booster'

In [5]:
df_feature_gain.head(50)

,features,scores
0,order_number-user_product_order_number_max,3013.204770
1,order_streak,1977.177110
2,user_product_bought_times/user_product_order_number_max-user_product_order_number_min,1046.690318
3,user_product_bought_times/user_order_count,873.581046
4,user_product_reorder_ratio,554.764738
5,user_product_order_number_max/user_order_number_max,203.444848
6,product_reorder_ratio,202.894738
7,department_reorder_ratio,142.264018
8,user_product_bought_times,120.233209
9,product_reorder_times,79.681468
10,aisle_reorder_ratio,73.569399
11,user_department_reorder_ratio,67.495951
12,user_aisle_reorder_ratio,62.782913
13,user_product/user_department_order_number_max,58.745132
14,product/department_reorder_ratio,52.905507
15,user_reorder_ratio,52.125381
16,days_since_prior_order,51.679532
17,department_days_since_prior_order_std,45.575313
18,user_product_days_since_prior_order/user_product_days_since_prior_order_mean,39.751303
19,department_order_dow_mean,39.660884
20,user_aisle_order_number_max/user_order_number_max,37.892330
21,user_product_order_number_max,37.862543
22,user_product_days_since_prior_order/user_product_days_since_prior_order_min,35.918855
23,product/aisle_reorder_ratio,33.353139
24,user_product_reorder_ratio/user_reorder_ratio,33.352989
25,product/department_reorder_times,32.668492
26,order_number,32.579875
27,department_order_count,30.028037
28,user_product/user_aisle_reorder_times,29.656973
29,user_product_order_number_min,28.825888
30,user_product/user_department_reorder_ratio,28.549715
31,user_aisle_reorder_ratio/user_reorder_ratio,28.067536
32,order_number-user_department_order_number_max,27.288926
33,product_add_to_cart_order_std,26.850155
34,user_product_count,25.426026
35,order_number-user_aisle_order_number_max,25.180517
36,product/aisle_bought_times,25.011304
37,user_aisle_order_number_min,24.964474
38,user_product_days_since_prior_order_mean,24.710151
39,user_department_order_number_max/user_order_number_max,24.563392
40,user_product/user_department_reorder_times,24.533105
41,product_days_since_prior_order_mean,24.025759
42,user_bought_times/user_active_days,23.388624
43,user_days_since_prior_order_mean,23.157276
44,user_product/user_aisle_order_number_max,23.101373
45,user_product_add_to_cart_order_mean/user_order_size_mean,22.305601
46,aisle_days_since_prior_order_std,22.166482
47,aisle_add_to_cart_order_std,21.789509
48,user_product_days_since_prior_order_min,21.728499
49,order_dow,21.343850

In [6]:
df_feature_weight = utils.get_feature_score(xgb_model._Booster.get_score())

In [9]:
df_feature_weight.head(20)

,features,scores
0,user_reorder_ratio,1147
1,user_product_days_since_prior_order/user_product_days_since_prior_order_mean,1044
2,user_add_to_cart_order_std,895
3,user_product_add_to_cart_order_mean/user_order_size_mean,815
4,user_product_days_since_prior_order/user_product_days_since_prior_order_min,803
5,days_since_prior_order,800
6,product_reorder_ratio,735
7,user_days_since_prior_order_std,703
8,user_product_bought_times/user_order_count,694
9,order_number-user_product_order_number_max,661
10,user_bought_times/user_active_days,647
11,product/aisle_bought_times,641
12,product_reorder_times,638
13,user_days_since_prior_order_mean,629
14,user_active_days,617
15,user_product_count,610
16,product_days_since_prior_order_mean,594
17,product/department_reorder_ratio,574
18,user_product_order_number_max/user_order_number_max,567
19,product_days_since_prior_order_std,562

In [5]:
for row in df_feature_gain.itertuples():
    if 'std' in row.features:
        print row.Index, row.features, row.scores

16 department_days_since_prior_order_std 84.8289307778
32 product_add_to_cart_order_std 36.4481177926
48 aisle_add_to_cart_order_std 27.5619442969
49 aisle_days_since_prior_order_std 27.5463520118
57 product_days_since_prior_order_std 24.406380546
60 user_days_since_prior_order_std 24.2705834264
61 user_add_to_cart_order_std 24.0061027176
63 department_order_hour_of_day_std 23.8107180473
76 user_product_days_since_prior_order_std 20.9381677161
80 department_add_to_cart_order_std 20.6753033333
81 department_order_dow_std 20.5793921136
95 product_order_dow_std 19.6606967974
96 aisle_order_dow_std 19.607493662
98 user_aisle_order_hour_of_day_std 19.2744529824
100 aisle_order_hour_of_day_std 19.044414727
101 user_aisle_add_to_cart_order_std 18.981012381
105 user_department_add_to_cart_order_std 18.8219313774
107 user_order_dow_std 18.7355520147
109 user_order_hour_of_day_std 18.7105898077
115 user_department_order_dow_std 18.0140228468
120 product_order_hour_of_day_std 17.6121658982
127 user_department_order_hour_of_day_std 17.2566424933
128 user_product_order_dow_std 17.2448561765
132 user_department_days_since_prior_order_std 16.8009646814
133 user_aisle_days_since_prior_order_std 16.7535519984
134 user_aisle_order_dow_std 16.5994807032
143 user_product_add_to_cart_order_std 15.1340465318
144 user_product_order_hour_of_day_std 14.7424747826

In [43]:
df_feature_gain.shape

(146, 2)

In [38]:
list(df_feature_gain.tail(66).features)

['department_add_to_cart_order_std',
 'department_order_dow_std',
 'user_aisle_days_since_prior_order_max',
 'aisle_add_to_cart_order_mean',
 'user_aisle_reorder_times',
 'aisle_order_dow_mean',
 'department_order_hour_of_day_mean',
 'user_department_days_since_prior_order_mean',
 'user_aisle_add_to_cart_order_mean/user_order_size_mean',
 'user_department_bought_times/user_bought_times',
 'product/aisle_add_to_cart_order_mean',
 'user_product/user_department_add_to_cart_order_mean',
 'user_product/user_aisle_add_to_cart_order_min',
 'user_product_add_to_cart_order_min/user_order_size_mean',
 'user_department_add_to_cart_order_min/user_order_size_mean',
 'product_order_dow_std',
 'aisle_order_dow_std',
 'aisle_active_days',
 'user_aisle_order_hour_of_day_std',
 'user_aisle_days_since_prior_order_min',
 'aisle_order_hour_of_day_std',
 'user_aisle_add_to_cart_order_std',
 'user_department_add_to_cart_order_mean',
 'user_order_dow_mean',
 'user_department_reorder_times',
 'user_department_add_to_cart_order_std',
 'user_department_order_number_min',
 'user_order_dow_std',
 'product_order_number_max',
 'user_order_hour_of_day_std',
 'user_product_add_to_cart_order_min',
 'user_product/user_aisle_order_number_min',
 'product_order_hour_of_day_mean',
 'department_product_count',
 'product_order_dow_mean',
 'user_department_order_dow_std',
 'user_product/user_aisle_reorder_ratio',
 'user_aisle_bought_times/user_bought_times',
 'user_department_add_to_cart_order_min',
 'user_department_add_to_cart_order_mean/user_order_size_mean',
 'product_order_hour_of_day_std',
 'user_product/user_department_add_to_cart_order_min',
 'user_order_hour_of_day_mean',
 'user_aisle_add_to_cart_order_min/user_order_size_mean',
 'user_aisle_add_to_cart_order_mean',
 'user_aisle_add_to_cart_order_min',
 'user_department_order_dow_mean',
 'user_department_order_hour_of_day_std',
 'user_product_order_dow_std',
 'user_product/user_department_bought_times',
 'user_product_add_to_cart_order_mean',
 'user_department_add_to_cart_order_max',
 'user_department_days_since_prior_order_std',
 'user_aisle_days_since_prior_order_std',
 'user_aisle_order_dow_std',
 'user_product_order_dow_mean',
 'user_department_order_hour_of_day_mean',
 'user_aisle_order_hour_of_day_mean',
 'user_aisle_add_to_cart_order_max',
 'user_aisle_order_dow_mean',
 'user_product_order_hour_of_day_mean',
 'aisle_id',
 'user_product/user_aisle_add_to_cart_order_mean',
 'user_product_add_to_cart_order_std',
 'user_product_order_hour_of_day_std',
 'user_product_add_to_cart_order_max']

In [40]:
df_feature_gain.tail(10)

                                           features     scores
136          user_department_order_hour_of_day_mean  16.424835
137               user_aisle_order_hour_of_day_mean  16.317000
138                user_aisle_add_to_cart_order_max  16.268719
139                       user_aisle_order_dow_mean  15.700316
140             user_product_order_hour_of_day_mean  15.666984
141                                        aisle_id  15.526122
142  user_product/user_aisle_add_to_cart_order_mean  15.457137
143              user_product_add_to_cart_order_std  15.134047
144              user_product_order_hour_of_day_std  14.742475
145              user_product_add_to_cart_order_max  11.963160

In [41]:
df_feature_weight.tail(10)

                                  features  scores
136               department_product_count      50
137      department_order_hour_of_day_mean      46
138              department_order_dow_mean      45
139               department_order_dow_std      44
140  user_department_add_to_cart_order_min      42
141      department_add_to_cart_order_mean      42
142       user_aisle_add_to_cart_order_min      41
143              user_product_bought_times      37
144       department_add_to_cart_order_std      36
145                 department_active_days      15

In [25]:
drop_col = ['user_order_count', 'user_product_reorder_times', 'user_order_number_max', 'user_bought_times', 'user_add_to_cart_order_mean', 'aisle_bought_times', 'department_bought_times', 'product_bought_times', 'department_reorder_times', 'user_aisle_bought_times', 'product_order_count', 'product/aisle_reorder_times', 'aisle_order_count', 'user_product_days_since_prior_order/user_product_days_since_prior_order_max', 'user_department_bought_times', 'aisle_reorder_times', 'user_id', 'user_department_order_number_max', 'product_active_days', 'product/department_bought_times']

In [26]:
df_val = pd.read_csv(INPUT_DIR+"validate_sample_std.csv")

In [28]:
no_use = df_val.columns[~df_val.columns.isin(df_feature_gain.features)]

In [30]:
no_use[~no_use.isin(drop_col)]

Index([u'label', u'product_product_count', u'aisle_order_number_max',
       u'department_order_number_max'],
      dtype='object')

In [7]:
df_feature_weight = utils.get_feature_score(xgb_model._Booster.get_fscore())

In [21]:
utils.get_feature_all_type_score('user_product_reorder_ratio/user_reorder_ratio', xgb_model)

total feature num: 146
weight
0.58904109589
                                         features  scores
85  user_product_reorder_ratio/user_reorder_ratio     158
gain
0.027397260274
                                        features      scores
3  user_product_reorder_ratio/user_reorder_ratio  838.211778
cover
0.219178082192
                                         features        scores
31  user_product_reorder_ratio/user_reorder_ratio  16504.934357

In [42]:
utils.get_feature_all_type_score('user_product_add_to_cart_order_max', xgb_model)

total feature num: 146
weight
0.835616438356
                               features  scores
121  user_product_add_to_cart_order_max      86
gain
1.0
                               features    scores
145  user_product_add_to_cart_order_max  11.96316
cover
1.0
                               features       scores
145  user_product_add_to_cart_order_max  1641.360655

In [18]:
utils.get_feature_all_type_score('user_product_bought_times/user_product_order_number_max-user_product_order_number_min', xgb_model)

total feature num: 146
weight
0.0684931506849
                                                                                features  \
9  user_product_bought_times/user_product_order_number_max-user_product_order_number_min

   scores
9     443
gain
0.013698630137
                                                                                features  \
1  user_product_bought_times/user_product_order_number_max-user_product_order_number_min

        scores
1  1219.453418
cover
0.0547945205479
                                                                                features  \
7  user_product_bought_times/user_product_order_number_max-user_product_order_number_min

         scores
7  27153.881486

In [48]:
name2 = 'XGBClassifier_colsample_bytree:0.8_learning_rate:0.1_max_depth:8_n_estimators:150_scale_pos_weight:2_seed:0_subsample:0.8_07-26-23-05-52.pkl'
xgb_model2 = utils.load_model(name2)

In [49]:
df_feature_gain2 = utils.get_feature_score(xgb_model2._Booster.get_score(importance_type='gain'))

In [55]:
df_feature_gain2.tail(20)

                                            features     scores
60        user_department_days_since_prior_order_max  19.316455
61           user_product_days_since_prior_order_min  19.227972
62                   user_days_since_prior_order_std  19.177606
63             user_product/user_aisle_reorder_times  19.152258
64                product_days_since_prior_order_std  18.940804
65                               aisle_product_count  18.909178
66         product/department_add_to_cart_order_mean  18.491309
67                  department_order_hour_of_day_std  18.406452
68            user_aisle_days_since_prior_order_mean  18.074337
69                      aisle_order_hour_of_day_mean  17.722728
70       user_aisle_reorder_ratio/user_reorder_ratio  17.543612
71                                        product_id  17.322574
72        user_department_days_since_prior_order_min  16.638041
73                                 order_hour_of_day  16.478203
74                     user_product_order_number_max  16.298167
75              user_product/user_aisle_bought_times  16.215708
76                            department_active_days  15.829234
77     user_product/user_department_order_number_min  15.734236
78  user_department_reorder_ratio/user_reorder_ratio  15.419279
79           user_product_days_since_prior_order_std  15.379358

In [56]:
df_feature_gain.tail(20)

                                           features     scores
126                  user_department_order_dow_mean  17.286406
127           user_department_order_hour_of_day_std  17.256642
128                      user_product_order_dow_std  17.244856
129       user_product/user_department_bought_times  17.111524
130             user_product_add_to_cart_order_mean  17.046808
131           user_department_add_to_cart_order_max  16.839214
132      user_department_days_since_prior_order_std  16.800965
133           user_aisle_days_since_prior_order_std  16.753552
134                        user_aisle_order_dow_std  16.599481
135                     user_product_order_dow_mean  16.451141
136          user_department_order_hour_of_day_mean  16.424835
137               user_aisle_order_hour_of_day_mean  16.317000
138                user_aisle_add_to_cart_order_max  16.268719
139                       user_aisle_order_dow_mean  15.700316
140             user_product_order_hour_of_day_mean  15.666984
141                                        aisle_id  15.526122
142  user_product/user_aisle_add_to_cart_order_mean  15.457137
143              user_product_add_to_cart_order_std  15.134047
144              user_product_order_hour_of_day_std  14.742475
145              user_product_add_to_cart_order_max  11.963160

In [32]:
df = pd.DataFrame({'user': [1, 1, 1], 'order': [4, 5, 6], 'product': [7, 8, 9]})

In [33]:
df = df.pivot(index='product', columns='order')

In [34]:
df

        user
order      4    5    6
product
7        1.0  NaN  NaN
8        NaN  1.0  NaN
9        NaN  NaN  1.0

In [35]:
df.columns = df.columns.droplevel(0)

In [36]:
df = df.fillna(-1)

In [37]:
df

order      4    5    6
product
7        1.0 -1.0 -1.0
8       -1.0  1.0 -1.0
9       -1.0 -1.0  1.0

In [39]:
df.diff(axis=1)

order     4    5    6
product
7       NaN -2.0  0.0
8       NaN  2.0 -2.0
9       NaN  0.0  2.0

In [50]:
x = np.abs(df.diff(axis=1).fillna(2)).values[:, ::-1]

In [59]:
np.abs(df.diff(axis=1).fillna(2)).values[:, ::]

array([[ 2.,  2.,  0.],
       [ 2.,  2.,  2.],
       [ 2.,  0.,  2.]])

In [55]:
np.abs(df.diff(axis=1).fillna(2)).values

array([[ 2.,  2.,  0.],
       [ 2.,  2.,  2.],
       [ 2.,  0.,  2.]])

In [57]:
x

array([[ 0.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  0.,  2.]])

In [52]:
np.argmax(x, axis=1)

array([1, 0, 0])

In [41]:
df

product
7   -1.0
8   -1.0
9    1.0
Name: 6, dtype: float64

In [27]:
reload(utils)

In [21]:
df_predict = pd.read_csv('../prediction/validate_diff.csv')

In [22]:
df_predict[df_predict.user_id == 203305]

         user_id  product_id     proba
14        203305       43154  0.981431
2276      203305       28204  0.954677
16937     203305       19660  0.898735
59762     203305       45007  0.798335
92775     203305       38383  0.735437
111949    203305        8518  0.702388
149254    203305       20876  0.645383
175046    203305       48679  0.609846
194565    203305       48335  0.585137
212018    203305        1938  0.563906
268250    203305       30233  0.503012
308846    203305       18362  0.464742
319356    203305       47990  0.455544
381022    203305       19019  0.406612
643043    203305       19678  0.256493
663245    203305        5456  0.247784
898442    203305       21376  0.164287
1101898   203305       19821  0.111514
1280809   203305       25890  0.076166
1479236   203305       28745  0.044621
1495306   203305       45437  0.042273
1573687   203305       20995  0.031072
1579616   203305        2780  0.030222
1626964   203305       29328  0.023006

In [15]:
df_predict_ground = pd.read_csv('../input/validate_sample_diff.csv')

In [17]:
df_predict_ground[df_predict_ground.user_id==186493][[UID, PID, 'label']]

      user_id  product_id  label
1491   186493       24852    1.0
1492   186493       47626    0.0
1493   186493       47766    0.0
1494   186493        5025    0.0
1495   186493       46787    0.0
1496   186493       13988    0.0
1497   186493       26497    0.0
1498   186493       19057    0.0
1499   186493       24943    0.0

In [73]:
df_result2 = predict.read_max_f1_analysis('../prediction/analysis_validate_diff_stack.csv')

In [78]:
df_result2['scores'] = df_result2.apply(predict.apply_f_score, axis=1)

In [89]:
print df_result2.shape, df_result2[df_result2.scores==0].shape

(26390, 4) (2882, 4)

In [80]:
df_result2

,user_id,true_products,products,scores
0,196610,"[196, 21292]","[196, 21292, 12341]",0.800000
1,166081,"[13080, 13176, 46554, 47209, 7217, 15700, 26376, 11844, 5456, 18070, 35951, 41950, 21783, 33731,...","[13176, 47209, 18070, 46554, 26376, 13080, 15700, 27104, 11844, 7217, 5484, 5456, 36554, 32177, ...",0.571429
2,179451,"[46149, 196]","[196, 46149]",1.000000
3,174620,"[13176, 19348, 10768, 19660, 19057, 39275, 25610, 23540, 21137, 36070]","[19660, 13176, 19348, 10768, 23540, 36070, 39275, 25610, 21137, 43961, 28494, 2086, 19057, 42265...",0.769231
4,178074,[19318],[19318],1.000000

In [97]:
low_result = df_result2[df_result2.scores < 0.3]

In [98]:
low_result

,user_id,true_products,products,scores
41,186915,"[36011, 27845, 42356, 15613, 46900]","[24852, 36011, 17461, 14218, 37646, 5020, 27845, 3283, 29370, 5077, 38622, 26790, 22035, 4920, 5...",0.170213
45,197190,"[24852, 6927, 8277, 46906, 47087, 22963, 33055, 17828, 44632]","[24852, 6927, 8277, 36714, 46906, 24799, 11123, 26165, 2091, 12341, 33055, 2383, 4836, 36076, 43...",0.262295
82,182291,"[27344, 30489, 46979, 22228, 41844, 10292, 37824, 30639, 42265, 8424]","[13176, 17630, 37824, 47209, 14778, 30489, 27845, 5491, 24561, 45066, 30967, 30192, 26790, 22298...",0.225352
114,170453,"[24852, 26209, 47626, 34969, 20114]","[24852, 35951, 15698, 1700, 45066, 37418, 26209, 21616, 47626, 48628, 46847, 48679, 5077, 8174, ...",0.270270
134,167698,[43154],"[24852, 47766, 43279, 31667, 19734, 28204, 3856, 45394, 18618, 31334, 34898, 13176, 40310, 39649...",0.000000
151,167071,"[46941, 788, 30183, 2245, 18988, 10391, 20298]","[788, 46941, 4447, 4006, 27240, 15424, 28441, 18988, 14097, 23915, 8920, 41784, 46131, 30183, 49...",0.250000
152,189059,"[27325, 19145, 5079, 33823]","[27325, 49235, 19145, 47626, 8193, 15547, 8195, 35042, 25985, 4443]",0.285714
245,186493,"[24852, 36961]","[24852, 47766, 46787, 26497, 47626, 5025, 6155, 13988, 42495, 17795, 36961, 3999, 13176, 28204]",0.250000
298,190075,"[36011, 34969, 47626, 24852, 46906, 5450]","[36011, 24852, 46906, 47626, 11576, 20114, 35921, 40571, 34969, 11777, 5450, 19057, 45066, 260, ...",0.142857
311,188762,[22089],"[22089, 37067, 23270, 30459, 5746, 5134, 47766, 8382, 19511, 26723, 2116, 35682]",0.153846
334,194411,"[41330, 45007, 34561, 18434]","[41330, 13176, 27966, 46979, 5785, 45007, 6568, 27325, 19156, 21038, 29987, 39558, 9477, 30233, ...",0.250000
349,184141,[None],"[46842, 2374, 20682, 20156, 11422, 29095, 41164, 17119, 44581, 28599, 24643, 40261]",0.000000
369,172653,"[30290, 45645, 14542]","[13176, 47209, 23383, 21709, 11980, 38647, 25670, 19057, 459, 27012, 27307, 45007, 41658, 10749,...",0.074074
375,172351,"[29447, 5450, 37067]","[29447, 45123, 37067, 5450, 21903, 14702, 22935, 19660, 44008, 17794, 21938, 16617, 9666, 23622,...",0.222222
391,169731,"[34197, 13176, 47209, 21906, 42450, 13852, 49241, 18011, 14992, 22950, 21137]","[34197, 47209, 13176, 27966, 11520, 24799, 28465, 43154, 45495, 32018, 38141, 21906, 7781, 42450...",0.237288
411,178510,"[24852, 46886, 34993, 49111, 43122, 47766]","[24852, 30233, 46886, 1463, 41787, 6187, 40198, 34993, 47766, 39408, 10840, 20127, 8859, 17183, ...",0.222222
435,192875,"[13176, 26604, 9871, 49075, 10749, 28123]","[13176, 14084, 311, 10337, 25890, 26604, 33000, 41618, 7035, 24489, 2361, 33120]",0.222222
450,169055,[36425],"[29509, 47141, 36425, 22164, 47873, 47979, 21709, 22943, 44819, 12817, 21376, 46331, 40541, 3408...",0.111111
460,178114,[None],"[19660, 37710, 13176, 43352, 31759]",0.000000
463,174066,"[26914, 42450, 47156, 17487, 43352, 5612, 2611, 21137, 8012, 13838, 18691, 9047, 20600, 19240, 4...","[36717, 33754, 44560, 21137, 24852, 3844, 26914, 44632, 47156, 42450, 26165, 17487, 22035, 24841...",0.292135
480,202538,"[24891, 40723, 33636, 28985, 42736, 28358, 47626]","[24891, 29370, 1553, 40723, 20118, 19155, 21043, 47766, 11440, 8518, 24852, 24561, 33636, 36724,...",0.222222
502,168607,"[24852, 47766, 9510, 16797, 33056, 24518]","[24852, 47766, 32605, 15290, 2005, 9510, 47626, 8514, 43645, 30038, 23729, 45149, 49683, 24442, ...",0.250000
509,173118,"[14233, 4692, 49192, 40326, 29013]","[14233, 4692, 27744, 9839, 17526, 40326, 49192, 47209, 29013, 45007, 2078, 38647, 33000, 7212, 4...",0.294118
521,177133,"[44460, 24852, 31678, 8736, 31416]","[8736, 44460, 24852, 26756, 5115, 41220, 35951, 19376, 21903, 35163, 24830, 44359, 19448, 1244, ...",0.142857
546,204723,"[24852, 14870, 9076, 14379, 43565, 47626, 33596, 28842, 43352]","[24852, 11155, 9387, 23909, 14870, 28481, 17341, 39613, 47626, 14890, 43565, 40001, 13966, 30696...",0.230769
555,180205,"[44632, 39947, 8324, 21376, 17730, 48335, 6375, 7503]","[44632, 13176, 39947, 49235, 23579, 20734, 22367, 30962, 24024, 22035, 14447, 18362, 22990, 4544...",0.181818
583,190666,"[24852, 1511, 47766, 27521, 26668, 40723, 32429, 26317, 39108, 5646, 35815, 890]","[24852, 1511, 47766, 5212, 40723, 30391, 32429, 24830, 26317, 48802, 26668, 48109, 48679, 22035,...",0.285714
613,199015,"[23783, 30630, 9825]","[13176, 27845, 23783, 18465, 40571, 21267, 46906, 30630, 13870, 22367, 43086, 4957, 41950, 21137...",0.200000
615,203378,"[2611, 14881, 30016, 24852, 20082, 44765, 21190, 17652, 10781, 42563, 17021, 27104, 32650]","[20082, 45066, 19359, 24852, 33754, 44765, 27966, 7403, 2611, 40268, 9411, 41238, 23687, 15902, ...",0.295082
625,178866,"[24852, 48628, 12341, 32138]","[24852, 21137, 7521, 32655, 41433, 37646, 38689, 49235, 32138, 43122, 12341, 37524, 365, 21417, ...",0.190476
...,...,...,...,...
26357,167293,[None],"[32175, 17341, 45061, 13866, 11292, 35458, 522, 43390]",0.000000
26359,193348,[None],"[15261, 33198, 29307, 21077, 16677, 48364, 4210, 43950, 12195, 43712]",0.000000
26360,177927,[None],"[24186, 12916, 44487, 33716, 38318, 24325, 47977, 28913, 38347, 40199, 16965, 34050, 9623, 44152...",0.000000
26361,184143,"[22275, 35943]","[21246, 17924, 13588, 28303, 26373, 30984, 41909, 35898]",0.000000
26362,179345,[48031],"[27086, 40332, 46979, 43183, 18234, 24703, 48031, 31683, 6359, 11679, 12630, 26040, 46041, 38455...",0.117647
26363,189444,"[23549, 23734]","[28464, 9076, 1940, 20463, 20842, 41844, 39646, 9007, 43409, 30183, 5750, 29429, 16797, 45004, 2...",0.133333
26364,205658,[None],"[None, 37427, 32638, 43741, 33771, 48395, 3243]",0.250000
26365,200246,[34789],"[35133, 8836, 44085, 13314, 16797, 33913, 34154, 24799, 22243, 29934, 36995, 5221, 3774, 31981, ...",0.054054
26367,178071,[None],"[8800, 34234, 40706, 16797, 49683, 45066, 39275, 41534, 46842, 35068, 12920, 13885, 39108, 121]",0.000000
26368,180667,[None],"[39204, 14203, 31066, 17283, 31268, 44775, 13176, 46109, 43409, 10242, 33610, 12824, 40592, 708,...",0.000000
26369,181064,"[44987, 25562]","[26209, 44987, 4920, 42625, 16797, 47141, 44799, 5025, 28938, 4086, 5450, 41950, 43352, 4605, 16...",0.054054
26370,176542,[18564],"[16759, 18564, 20632, 3793, 32433, 47804, 45646, 4288, 5127]",0.200000
26371,172950,[23734],"[18078, 28842, 45788, 24852, 23734, 7156, 37022, 39984, 18880, 28137, 4769, 18610, 18418, 45066]",0.133333
26372,169635,"[34748, 4606, 25146]","[44166, 33298, 31136, 20711, 26646, 16327, 48210, 18523, 14325, 11034, 40571, 36011, 24852, 2036...",0.097561
26373,191838,[None],"[22935, 36534, 34243, 29217, 49351, 43295, 45007, 24129, 8518, 27336, 22081, 1208, 47209, 28985,...",0.000000
26374,165608,[None],"[8193, 44142, 26209, 5479, 31717, 34590, 38777, 16797, 21288, 27156, 18090, 39275, 15613, 24221,...",0.000000
26375,170833,[None],"[None, 32156, 22617, 37818, 43948, 7644, 44328, 12817, 17616]",0.200000
26376,194038,[36107],"[34355, 17769, 47141, 43295, 25160, 43406, 36107, 31981, 24852, 7736, 14233, 47656, 22886, 27294...",0.095238
26377,190817,[None],"[16797, 24964, 15290, 23734, 2295, 5876, 47788, 27104, 7175, 7628, 22144, 47734, 34190, 12204, 4...",0.000000
26378,205337,[5744],"[None, 40332, 25513, 37766, 8518]",0.000000
26379,168697,[None],"[4799, 42701, 6104, 12206, 9020, 26384, 33509, 43749, 21137, 30745, 47766, 12341, 26209, 25659, ...",0.000000
26380,204599,"[49683, 47766]","[21903, 25466, 28204, 5077, 47766, 27845, 40174, 41649, 42193, 24852, 16797, 3957, 42265, 25146,...",0.074074
26381,167951,[41376],"[17872, 34197, 22308, 13176, 35951, 22416, 36869, 19660, 39475, 44987, 41271, 7054, 31015, 27845...",0.033898
26382,198097,[None],"[43967, 10333, 25986, 34862, 19173, 28836, 43070, 45296, 39041, 19005, 24615, 18790, 29432, 8153]",0.000000
26383,167399,[9088],"[None, 1525, 16959, 9088, 25464, 43083, 20864, 42809, 2214, 42117, 10566, 500]",0.153846
26384,199251,[12480],[None],0.000000
26385,204340,"[15622, 22395]","[49235, 38433, 28572, 46522, 15622, 6052, 2915]",0.222222
26386,182854,"[31506, 14168]","[31506, 27479, 15134, 29835, 4210, 2519, 44548, 38579, 29581, 18698, 22788, 23734, 48805, 43187,...",0.043478
26387,174210,"[48667, 13194]","[44337, 27478, 21195, 9156, 35011, 48667, 36736, 10646, 47396, 13194, 1295, 48118]",0.285714
26388,194445,[None],"[32331, 13187, 47111, 15924, 1217, 325, 25999, 21333, 5077, 40376, 17820, 22422, 27423, 10957, 1...",0.000000

In [103]:
low_result.ix[41].products

[24852,
 36011,
 17461,
 14218,
 37646,
 5020,
 27845,
 3283,
 29370,
 5077,
 38622,
 26790,
 22035,
 4920,
 5550,
 16254,
 48395,
 41220,
 47621,
 15613,
 45767,
 31683,
 36287,
 42265,
 47626,
 42110,
 46720,
 48171,
 33043,
 42356,
 30391,
 30967,
 33000,
 21903,
 5499,
 40706,
 17155,
 32230,
 18441,
 43504,
 32734,
 12576]

In [110]:
a = df_predict[df_predict.user_id==186915]
a[a.index >= 226064]

         user_id  product_id     proba
226064    186915       42356  0.547691
258915    186915       33000  0.512339
269395    186915        5499  0.501802
274321    186915       40706  0.496817
274506    186915       32230  0.496628
276421    186915       33043  0.494758
277560    186915       30967  0.493663
301840    186915       17155  0.471048
321297    186915       43504  0.453935
343855    186915       32734  0.435168
356306    186915       34969  0.425316
363203    186915        8518  0.420079
370348    186915       38273  0.414607
406602    186915       18441  0.388274
440697    186915        4799  0.365255
459446    186915        2825  0.353027
459802    186915       13535  0.352813
466935    186915       12206  0.348343
477665    186915       44371  0.341632
482418    186915        8193  0.338805
484588    186915       25162  0.337517
506804    186915       31343  0.324563
519785    186915        3976  0.317402
521403    186915        9076  0.316517
532784    186915       43789  0.310270
542380    186915       12576  0.305191
559700    186915       28986  0.296235
570457    186915       44422  0.290815
668021    186915       14633  0.245820
671759    186915       44449  0.244242
674202    186915       32433  0.243222
680803    186915       48287  0.240575
743084    186915       10644  0.215949
754761    186915       20995  0.211711
793269    186915        1090  0.197964
809905    186915       32691  0.192249
824898    186915       49164  0.187207
837429    186915       13838  0.183109
849166    186915       17828  0.179388
852978    186915       42625  0.178174
877712    186915       18370  0.170490
908594    186915       44424  0.161287
937489    186915       35887  0.153038
980618    186915       44949  0.141251
1001205   186915       12872  0.135810
1002998   186915        9881  0.135358
1009396   186915       14332  0.133721
1014593   186915       46900  0.132409
1033721   186915       49533  0.127612
1066846   186915       28571  0.119594
1128894   186915       44628  0.105556
1129542   186915       14992  0.105418
1133403   186915       16823  0.104604
1178422   186915       30489  0.095289
1179714   186915        8006  0.095033
1202481   186915       25890  0.090530
1217179   186915       23537  0.087699
1237146   186915       44097  0.084000
1239863   186915       18557  0.083502
1260168   186915       49585  0.079803
1286821   186915       20345  0.075138
1288541   186915        2447  0.074844
1300126   186915       46676  0.072855
1314318   186915       35898  0.070471
1339535   186915       39469  0.066229
1350317   186915       49683  0.064452
1365026   186915         890  0.062062
1382643   186915        5212  0.059302
1386055   186915       36793  0.058763
1390026   186915        9122  0.058146
1398098   186915       37458  0.056917
1410458   186915       37158  0.055017
1423982   186915        4605  0.052946
1444116   186915        5025  0.049883
1506306   186915       42701  0.040673
1515819   186915       24009  0.039310
1533437   186915       44643  0.036783
1538565   186915       27596  0.036069
1539645   186915          34  0.035918
1549598   186915       46820  0.034518
1557439   186915       13733  0.033397
1573147   186915       43463  0.031148
1607124   186915         204  0.026143
1626522   186915        2450  0.023079
1629392   186915         276  0.022605
1641163   186915       29594  0.020553
1650598   186915       13853  0.018801
1651089   186915       35940  0.018698
1653307   186915         248  0.018271
1657056   186915       15405  0.017516
1666582   186915       29079  0.015470
1667974   186915        7179  0.015151

In [85]:
low_result[low_result.user_id==178114]

,user_id,true_products,products,scores
349,184141,[None],"[46842, 2374, 20682, 20156, 11422, 29095, 41164, 17119, 44581, 28599, 24643, 40261]",0.0

In [92]:
df_predict[df_predict.user_id==184141]

         user_id  product_id     proba
1958      184141       46842  0.956777
3132      184141        2374  0.949532
11661     184141       20682  0.914766
17602     184141       20156  0.896874
21906     184141       29095  0.885112
37702     184141       11422  0.846020
73187     184141       17119  0.771693
86007     184141       41164  0.747816
108621    184141       44581  0.708115
151759    184141       24643  0.641686
206200    184141       28599  0.570776
214961    184141       40261  0.560423
460435    184141       45037  0.352400
614991    184141        4986  0.269250
621785    184141        9641  0.266070
919326    184141       31210  0.158167
936687    184141       28221  0.153254
1056223   184141       27681  0.122129
1194273   184141       33474  0.092155
1214844   184141       46811  0.088156
1315203   184141       17242  0.070320
1363417   184141       32762  0.062318
1390863   184141       20590  0.058015
1426988   184141        4006  0.052474
1453070   184141       17341  0.048519
1460764   184141       20253  0.047373
1503999   184141        3919  0.041000
1509798   184141       46676  0.040164
1563773   184141        7295  0.032493
1605786   184141       13950  0.026349
1636510   184141       23789  0.021379
1661881   184141       25776  0.016495

In [116]:
df_result3 = predict.read_max_f1_analysis('../prediction/analysis_07-31-00-44-24_validate_diff_stack.csv')

In [123]:
target_index = df_result3.apply(lambda row: True if (row['scores'] < 0.3 and row['products'][0] is None) else False, axis=1)
df_result3[target_index]

,user_id,true_products,products,scores
23673,193703,[29265],"[None, 44632]",0.000000
23687,176635,"[16349, 8955, 13780, 36070, 31562, 2846, 48364, 790, 20114, 15261]","[None, 25747]",0.000000
23757,196508,[44683],"[None, 31102]",0.000000
23761,194912,[45232],"[None, 196]",0.000000
23774,195623,[31268],"[None, 35301]",0.000000
23836,180726,"[29090, 23204, 25144]","[None, 1875]",0.000000
23883,192727,"[35923, 29744, 29307, 8475, 49198, 35171, 39993]","[None, 30587]",0.000000
23928,187309,[16759],"[None, 16797]",0.000000
24032,173815,"[15424, 9558, 24852]","[None, 21137]",0.000000
24037,198350,"[27841, 2512]","[None, 5818]",0.000000
24049,166933,"[27086, 30633, 39450, 49324, 32275, 41315, 4837, 17044, 11030]","[None, 27086]",0.181818
24056,170181,"[7559, 40280]","[None, 27845]",0.000000
24071,198762,[21333],"[None, 6774]",0.000000
24100,174198,"[24952, 40992]","[None, 4914]",0.000000
24149,190928,"[21137, 18891, 32579]","[None, 20244]",0.000000
24185,199728,"[16816, 38154]","[None, 5818]",0.000000
24233,185421,[24004],"[None, 32650]",0.000000
24236,204803,"[35140, 23484]","[None, 27845]",0.000000
24243,175160,[44359],"[None, 28985]",0.000000
24254,171482,[37427],"[None, 47877]",0.000000
24261,189288,[28553],"[None, 35997]",0.000000
24293,177311,[37646],"[None, 23288]",0.000000
24303,185146,"[36550, 6489, 12075, 35425]","[None, 24852]",0.000000
24316,186592,[29487],"[None, 43662]",0.000000
24322,171939,"[14129, 43295, 3188, 4472, 12916]","[None, 43295]",0.285714
24324,167472,"[23909, 41787, 28967, 30489, 34128, 343]","[None, 23909]",0.250000
24327,181072,[7987],"[None, 6369]",0.000000
24335,204821,"[48720, 19135]","[None, 5438]",0.000000
24337,193959,"[28993, 45661, 449, 29026, 2997]","[None, 311]",0.000000
24347,173580,"[40332, 27196, 43154, 37262, 47144, 20738, 9558]","[None, 27196]",0.222222
24373,172348,"[42240, 47977, 29848]","[None, 13176]",0.000000
24377,203524,[36425],"[None, 4047]",0.000000
24392,167403,"[4058, 38739]","[None, 49534]",0.000000
24432,188584,[45832],"[None, 8736]",0.000000
24458,188700,[13780],"[None, 21850]",0.000000
24465,204800,[9170],"[None, 10702]",0.000000
24512,186849,"[12341, 21903]","[None, 22900]",0.000000
24534,195572,"[49683, 32833, 10326, 29487, 12508]","[None, 45]",0.000000
24560,174905,"[33153, 42781]","[None, 29447]",0.000000
24582,193723,"[14897, 47766]","[None, 21709]",0.000000
24587,174164,[19348],"[None, 14519]",0.000000
24614,201982,"[35900, 12606]","[None, 29487]",0.000000
24615,179039,"[16797, 2846]","[None, 24852]",0.000000
24630,166924,"[13093, 30489, 17044, 41004, 27344]","[None, 16521]",0.000000
24635,184589,"[35547, 21137, 46616, 2314]","[None, 47766]",0.000000
24643,173026,[47977],"[None, 33198]",0.000000
24652,192972,"[32303, 3603, 7644, 352, 41111]","[None, 7644]",0.285714
24685,168534,"[13176, 29615, 32655, 4675, 46226, 19057, 19086, 32467, 48364, 210]","[None, 13176]",0.166667
24701,197524,[21131],"[None, 41276]",0.000000
24721,175512,[39275],"[None, 35921]",0.000000
...,...,...,...,...
26284,180078,[13643],[None],0.000000
26288,196661,"[19171, 44008, 7781, 9020, 26040]",[None],0.000000
26289,203123,"[28985, 16759, 6341, 44987, 47626]",[None],0.000000
26295,185878,"[21501, 18790]",[None],0.000000
26296,202334,"[6473, 31487, 30553, 41131, 46088]",[None],0.000000
26297,174732,[34126],[None],0.000000
26298,196899,"[18432, 16486, 23729]",[None],0.000000
26302,201967,[28572],[None],0.000000
26303,177827,"[27086, 2962, 2670]",[None],0.000000
26304,195238,"[27020, 4920]",[None],0.000000
26306,199040,"[9358, 13259, 42803]",[None],0.000000
26308,181253,[8379],[None],0.000000
26311,183674,[28842],[None],0.000000
26315,191796,"[38684, 4086]",[None],0.000000
26317,169931,"[26209, 33065]",[None],0.000000
26319,199149,"[35600, 15869]",[None],0.000000
26321,200171,[33198],[None],0.000000
26322,193543,"[29794, 30731]",[None],0.000000
26323,169166,[37248],[None],0.000000
26324,187421,"[35898, 10895]",[None],0.000000
26325,186049,"[37731, 24852, 23729]",[None],0.000000
26326,188458,[6729],[None],0.000000
26329,191230,[13603],[None],0.000000
26330,185549,"[9114, 36425]",[None],0.000000
26331,197215,"[45603, 8736, 33911, 9421]",[None],0.000000
26335,202012,[28876],[None],0.000000
26337,204614,[31422],[None],0.000000
26340,179449,"[3413, 3318]",[None],0.000000
26341,197904,[19003],[None],0.000000
26344,196614,[22497],[None],0.000000
26348,173010,"[19068, 27714]",[None],0.000000
26351,168083,[27680],[None],0.000000
26352,174083,"[19086, 9076, 49683, 44142, 3541]",[None],0.000000
26361,184143,"[22275, 35943]",[None],0.000000
26362,179345,[48031],[None],0.000000
26363,189444,"[23549, 23734]",[None],0.000000
26365,200246,[34789],[None],0.000000
26369,181064,"[44987, 25562]",[None],0.000000
26370,176542,[18564],[None],0.000000
26371,172950,[23734],[None],0.000000
26372,169635,"[34748, 4606, 25146]",[None],0.000000
26376,194038,[36107],[None],0.000000
26378,205337,[5744],[None],0.000000
26380,204599,"[49683, 47766]",[None],0.000000
26381,167951,[41376],[None],0.000000
26383,167399,[9088],[None],0.000000
26384,199251,[12480],[None],0.000000
26385,204340,"[15622, 22395]",[None],0.000000
26386,182854,"[31506, 14168]",[None],0.000000
26387,174210,"[48667, 13194]",[None],0.000000

In [118]:
df_predict[df_predict.user_id==196661]

         user_id  product_id     proba
424425    196661       44008  0.376068
441684    196661        9020  0.364622
500472    196661       24852  0.328261
559419    196661       13263  0.296395
560743    196661       25985  0.295702
708695    196661        7781  0.229177
765604    196661       18362  0.207725
790469    196661       20842  0.198932
815919    196661       19171  0.190203
837298    196661       45965  0.183152
864848    196661       30021  0.174471
867501    196661       38579  0.173638
897630    196661       18027  0.164533
1017584   196661       42240  0.131626
1036045   196661       14852  0.127044
1060327   196661       29252  0.121152
1094996   196661       26040  0.113098
1097929   196661       29642  0.112422
1106990   196661       23801  0.110371
1118134   196661       18201  0.107889
1122145   196661       49269  0.107004
1123793   196661        9366  0.106647
1148132   196661       49683  0.101487
1149597   196661       12448  0.101181
1167883   196661       34312  0.097423
1221292   196661        2180  0.086934
1555806   196661       30458  0.033633

In [126]:
df_result3[df_result3.user_id==203123]

       user_id                       true_products products  scores
26289   203123  [28985, 16759, 6341, 44987, 47626]   [None]     0.0

In [129]:
type(df_predict[df_predict.user_id==203123])

pandas.core.frame.DataFrame

In [130]:
reload(predict)

In [131]:
predict.get_true_product_pred_proba(203123, [28985, 16759, 6341, 44987, 47626], df_predict)

         user_id  product_id     proba
818579    203123       44987  0.189334
980818    203123       47626  0.141200
1129622   203123       28985  0.105403
1163529   203123        6341  0.098307
1234412   203123       16759  0.084498